### ISSUE TITLE
Cannot run the example/test notebooks

### ISSUE THREAD

**Issue by simon-sat** [LDEO-CREW/Pythonic-DISORT#11]
Hello,
I have installed `Pythonic-DISORT` by cloning the repo and running `pip install -r all_optional_dependencies.txt`

I then tried to run the example notebook `1a_test` but get this error:
```
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
Cell In[1], line 2
      1 import PythonicDISORT
----> 2 import disort
      3 import numpy as np
      4 import matplotlib.pyplot as plt

ModuleNotFoundError: No module named 'disort'
```

The installation went smoothly, so I am unsure why I get this `ModuleNotFoundError`. Could you please look into it?

**Comment by dhjx1996** [comment]
The `disort` module is the Python-wrapped DISORT. Unfortunately, installation of that module is system-dependent and users will need to separately install FORTRAN compilers. Thus, it is not installed with PythonicDISORT and is in fact not part of PythonicDISORT. If you would like to get that running, however, I will most certainly be happy to help.

The test reference solutions from DISORT have been saved in .npz files in the `pydisotest` directory though, and so you can run `pytest` in that directory without needing the `disort` module.

**Comment by RobertPincus** [comment]
@simonrp84, @dhjx1996 and I discussed this further, and he may split the notebooks into those doing validation against the Fortran code and those demonstrating the use of PythonicDisort more generally.

**Comment by simon-sat** [comment]
Yes, I think that would be a good idea - it wasn't immediately clear to me that those notebooks were for testing rather than as examples for  users.

**Comment by dhjx1996** [comment]
Sounds good! I will revamp the current test notebooks into examples for users and remove `disort4.0.99_f2py` and all references to the `disort` module to avoid licensing issues. I may make some changes to how the tests are conducted but there will still be automated tests at the very least.

**Comment by dhjx1996** [comment]
I have removed `disort4.0.99_f2py` from both the repository and the entire repository history. I have kept the `.npz` reference solutions in the repository but greatly reduced their size. These changes are not final, but at least now the Jupyter Notebooks should all run regardless of whether a F2py-wrapped Stamnes' DISORT is installed.

**Comment by dhjx1996** [comment]
The test suite may undergo further changes but the initial problem has been resolved.

**Comment by simon-sat** [comment]
Apologies for not closing this myself, thanks for the work on it.
