### ISSUE TITLE
Unable to import distort

### ISSUE THREAD

**Issue by ghost** [LDEO-CREW/Pythonic-DISORT#12]
Hi, I'm a newbie and I'm learning the Pythonic-DISORT using Jupyter notebook. it's going fine for me but when I got to chapter 6;
"Comparisons against Stamnes’ DISORT", I was unable to import disort. I see disort4.0.99_f2py directory in your GitHub repository but don't know how to go about it. 
any help will be greatly appreciated .

**Comment by dhjx1996** [comment]
Hi, the Jupyter Notebooks should now work regardless of whether a F2py-wrapped Stamnes' DISORT is installed
