### ISSUE TITLE
Speed up the for-loops in PythonicDISORT using the fact that many np.linalg functions can act on a list of matrices

### ISSUE THREAD

**Issue by dhjx1996** [LDEO-CREW/Pythonic-DISORT#6]
As of NumPy version 1.8.0 (remember to update requirements), `np.linalg.eig([list of matrices])` will output a list of the eigenpairs for each matrix. This is much faster than using a python for-loop. This should work for many other np.linalg functions as well, see https://numpy.org/doc/stable/reference/routines.linalg.html#module-numpy.linalg.

PythonicDISORT will still require for-loops to assemble the various systems to be solved, but we can potentially speed the algorithm up greatly by using the above on the linear algebra operations which are the most expensive parts of each loop.

**Comment by Maths2209** [comment]
Idea: Break each of "_loop_and_assemble_results.py" and "_one_Fourier_mode.py" into two. Preserve the loops to generate the required matrices. Assemble the matrices into tensors. Use "np.linalg.eig([list of matrices])" and "np.tensorsolve" to solve looplessly.

**Comment by dhjx1996** [comment]
Done for the loops over the atmospheric layers (inside __one_Fourier_mode.py_).
